routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//home page routes
Route::get('/', 'HomePageController@index')->name('home.page');
Route::view('challenge/smart/unir', 'home_page/challenge_smart_unir')->name('challenge.smart.unir');
Route::view('programme/campagne', 'home_page/programme')->name('programme.campagne');
Route::view('croire/en/togo', 'home_page/croire')->name('croire');
Route::view('osons/davantage', 'home_page/osons_davantage')->name('osons');
Route::view('mot/president', 'home_page/mot_president')->name('mot.president');

Route::get('coming-soon/index', 'ComingSoonController@index')->name('coming_soon');

// Newsletter routes
Route::get('newsletter/store', 'Admin\NewsletterController@store')->name('store.newsletter');
Route::post('newsletter/store', 'Admin\NewsletterController@_store')->name('admin.store.newsletter');

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    Auth::routes();
    Route::get('/home', 'AdminHomeController@index')->name('home');
    Route::resource('buttons', 'ButtonController');

    Route::post('slide/position/update', 'SlideController@update_slide_position');
    Route::resource('slides', 'SlideController');

    Route::resource('newsletters', 'NewsletterController');
    Route::resource('newsletterMessages', 'NewsletterMessageController');

    Route::resource('parameters', 'ParameterController');
});

app/Models/Slide.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Support\Facades\Auth;

/**
 * Class Slide
 * @package App\Models
 * @version January 16, 2020, 1:13 pm UTC
 *
 * @property string image
 * @property string title1
 * @property string title2
 * @property string button_label
 * @property string button_link
 * @property integer image_position
 */
class Slide extends Model
{

    public $table = 'slides';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';
//    const MAX_IMAGE_SIZE = 8000000;
   /* const MAX_IMAGE_SIZE = 8000000;
    const IMAGE_WIDTH = 1920;
    const IMAGE_HEIGHT = 1270;*/


    public $fillable = [
        'image',
        'title1',
        'title2',
        'button_label',
        'button_link',
        'button_color',
        'slide_position'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'image' => 'string',
        'title1' => 'string',
        'title2' => 'string',
        'button_label' => 'string',
        'button_link' => 'string',
        'button_color' => 'string',
        'slide_position' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
       /* 'title1' => 'required',
        'title2' => 'required',
        'button_label' => 'required',*/

    ];

    public function getImageUrlAttribute()
    {
        return asset('storage/slides/'. $this->image);
    }
}

app/Http/Controllers/Admin/SlideController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\Admin\SlideDataTable;
use App\Http\Requests\Admin\CreateSlideRequest;
use App\Http\Requests\Admin\UpdateSlideRequest;
use App\Models\Slide;
use App\Repositories\Admin\SlideRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Response;

class SlideController extends AppBaseController
{
    /** @var  SlideRepository */
    private $slideRepository;

    public function __construct(SlideRepository $slideRepo)
    {
        $this->middleware('auth:' . \App\Models\Admin::GUARD);

        $this->slideRepository = $slideRepo;
    }

    /**
     * Display a listing of the Slide.
     *
     * @param SlideDataTable $slideDataTable
     * @return Response
     */
    public function index(SlideDataTable $slideDataTable)
    {
        $slides = Slide::orderBy('slide_position', 'ASC')->select('id', 'image', 'title1', 'title2', 'button_label',
            'button_link', 'button_color', 'slide_position')->get();
        return $slideDataTable->render('admins.slides.index', compact('slides'));
    }

    public function update_slide_position(Request $request)
    {
        $slides = Slide::all();
        foreach ($slides as $slide){
            $slide->timestamps = false;
            $id = $slide->id;

            foreach ($request->positions as $position){
                if ($position['id'] == $id)
                    $slide->update(['slide_position' => $position['position']]);
            }
        }
    }
    /**
     * Show the form for creating a new Slide.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('admins.slides.create');
    }

    /**
     * Store a newly created Slide in storage.
     *
     * @param CreateSlideRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CreateSlideRequest $request)
    {

        if (!$request['button_color']){
            $request['button_color'] = 'color4';
        }
        if ($request->hasFile('image')){
            $image = $request->file('image');
            if ($this->is_image_allowed($image)){
                $image_name = (String)Str::uuid() . '.' . $image->getClientOriginalExtension();
                $image->storeAs('public/slides/' , $image_name);

                $this->slideRepository->create([
                    'image' => $image_name,
                    'title1' => $request['title1'],
                    'title2' => $request['title2'],
                    'button_label' => $request['button_label'],
                    'button_link' => $request['button_link'],
                    'button_color' => $request['button_color'],
                    'slide_position' => Slide::all()->count() + 1,
                ]);
                Flash::success('Slide saved successfully.');
            }
            else
                Flash::success('Slide saved fail.');
        }
        return redirect(route('admin.slides.index'));
    }

    /**
     * Verify if the specified file type is image
     * @param UploadedFile $image
     * @return bool
     */
    public function is_image_allowed(UploadedFile $image)
    {
        $mime_type = $image->getClientMimeType();
        // list($width, $height) = getimagesize($image);
        //return Str::startsWith($mime_type, 'image') && $width == Slide::IMAGE_WIDTH
        //   && $height == Slide::IMAGE_HEIGHT && $image->getSize() <= Slide::MAX_IMAGE_SIZE;
        return Str::startsWith($mime_type, 'image/');
    }

    /**
     * Display the specified Slide.
     *
     * @param  int $id
     *
     * @return \Illuminate\Routing\Redirector|\Illuminate\View\View|Response
     */
    public function show($id)
    {
        $slide = $this->slideRepository->find($id);

        if (empty($slide)) {
            Flash::error('Slide not found');

            return redirect(route('admin.slides.index'));
        }

        return view('admins.slides.show')->with('slide', $slide);
    }

    /**
     * Show the form for editing the specified Slide.
     *
     * @param  int $id
     *
     * @return\Illuminate\Routing\Redirector|\Illuminate\View\View
     */
    public function edit($id)
    {
        $slide = $this->slideRepository->find($id);

        if (empty($slide)) {
            Flash::error('Slide not found');

            return redirect(route('admin.slides.index'));
        }
        return view('admins.slides.edit', compact('slide'));
    }

    /**
     * Update the specified Slide in storage.
     *
     * @param  int              $id
     * @param UpdateSlideRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update($id, UpdateSlideRequest $request)
    {
        $slide = $this->slideRepository->find($id);
//        dd($slide);
        $image_name = "";
        if (empty($slide)) {
            Flash::error('Slide not found');

            return redirect(route('admin.slides.index'));
        }
        if ($request->hasFile('image')){
            $image = $request->file('image');
            if ($this->is_image_allowed($image)) {
                Storage::delete('public/slides/' .$slide->image);
                $image_name = (String)Str::uuid() . '.' . $image->getClientOriginalExtension();
                $image->storeAs('public/slides/', $image_name);
            }
            $this->slideRepository->update(
                [
                    'image' => $image_name,
                    'title1' => $request['title1'],
                    'title2' => $request['title2'],
                    'button_label' => $request['button_label'],
                    'button_link' => $request['button_link'],
                    'button_color' => $request['button_color'],
                    'slide_position' => $request['slide_position'],
                ], $id);

            Flash::success('Slide updated successfully.');
        }
        else{
            $this->slideRepository->update($request->all(), $id);
        }
        return redirect(route('admin.slides.index'));
    }

    /**
     * Remove the specified Slide from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Exception
     */

    public function destroy($id)
    {
        $slide = $this->slideRepository->find($id);

        if (empty($slide)) {
            Flash::error('Slide not found');

            return redirect(route('admin.slides.index'));
        }

        $this->slideRepository->delete($id);
        Storage::delete('public/slides/' .$slide->image);

        Flash::success('Slide deleted successfully.');

        return redirect(route('admin.slides.index'));
    }
}

resources/views/admins/slides/create.blade.php
@extends('admins.layouts.app')

@section('title')
    Create Slide
@endsection

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('admin.slides.index') !!}">Slide</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Slide</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'admin.slides.store', 'enctype' => 'multipart/form-data']) !!}

                                   @include('admins.slides.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/admins/slides/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.slides.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('admin.slides.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('admin.slides.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
    ]) !!}
</div>
{!! Form::close() !!}

<script type='text/javascript'>
    $(document).on("submit", "form", function (e) {
        e.preventDefault();
        Swal.fire({
            title: "{{__('Are you sure?') }}",
            html: "{{__('You won\'t be able to revert this!') }}",
            width: 400,
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#cbc7c1',
            confirmButtonText: "{{ __('Yes') }}",
            cancelButtonText: "{{ __('Cancel') }}",
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                e.currentTarget.submit();
            }
        });
    });
</script>

resources/views/admins/slides/edit.blade.php
@extends('admins.layouts.app')

@section('title')
   Edit Slide
@endsection

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('admin.slides.index') !!}">Slide</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Slide</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($slide, ['route' => ['admin.slides.update', $slide->id],  'enctype' => 'multipart/form-data',
                                    'method' => 'patch']) !!}

                              <!-- Image Field -->
                                  <div class="form-group">
                                      <a data-toggle="dropdown" href="#">
                                          <img class="img-fluid width: 100%" src="{{ $slide->image_url }}" alt="" width="570"
                                               height="300" style="margin-bottom: 20px"/>
                                      </a>
                                  </div>
                                <p style="color: #004cd6">Servez vous du champs <b>Image</b> pour changer l'image </p>
                                  @include('admins.slides.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/admins/slides/fields.blade.php
<!-- Image Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('image', __('Image:')) !!}</b>
    {!! Form::file('image', ['id' => 'image', 'class' => 'form-control', 'accept' => 'image/*']) !!}
</div>

<!-- Title1 Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('title1', __('Title 1:')) !!}</b>
    {!! Form::text('title1', null, ['class' => 'form-control']) !!}
</div>

<!-- Title2 Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('title2', __('Title 2:')) !!}</b>
    {!! Form::text('title2', null, ['class' => 'form-control']) !!}
</div>

<!-- Button Label Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('button_label', __('Button label:')) !!}</b>
    {!! Form::text('button_label', null, ['class' => 'form-control']) !!}
</div>

<!-- Button Link Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('button_link', __('Button link:')) !!}</b>
    {!! Form::text('button_link', null, ['class' => 'form-control']) !!}
</div>

<!-- -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('color', __('Button color:')) !!}</b>
    {!! Form::select('button_color', \App\Models\Button::COLORS,
        null, ['placeholder' => __('Select the color'),'class' => 'form-control'])
    !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('Save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('admin.slides.index') }}" class="btn btn-secondary">{{__('Cancel')}}</a>
</div>
@section('styles')
    <link rel="stylesheet" href="{{ asset('template/css/selectize.bootstrap3.min.css') }}"/>
@endsection

<!-- Allows to search an option in select field -->
@section('scripts')
    <script src="{{ asset('template/js/selectize.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('select').selectize({
                sortField: 'text'
            });
        });
    </script>

   {{-- <script type="text/javascript">
        /** image constraints
         * */
        $(document).on('submit', 'form', function (e) {
            var uploaded_image = document.getElementById('image');
            var infos = "";
            var display = false;
            var width = "{{ $image_width }}";
            var height = "{{ $image_height }}";
            var max_image_size = "{{ $max_image_size }}";
            var size_not_allowed = false;

            if (uploaded_image.size > parseInt(max_image_size)) {
                infos += "L'image est trop lourde";
                display = true;
                size_not_allowed = true;

            }
            if (size_not_allowed){
                infos +=  "Vous ne pouvez charger qu'un maximum de 8 Mo";
            }
            if(uploaded_image.height < parseInt(height) || uploaded_image.width < parseInt(width) ){
                infos += "Les dimensions de l'image doivent etre : " + "<br>";
                infos +="hauteur >= "+ height+ "<br>";
                infos += "largeur >= : "+ width +"<br>";
                infos += "Si vous continuez votre SLIDE ne sera pas enregistré" +  "<br>";
                display = true;
            }

            if(display){
                e.preventDefault();

                Swal.fire({
                    type: 'warning',
                    title: "warning",
                    html: "<div style='font-size: 15px'>" + infos + "</div>",
                    width: 400,
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: "Continuer",
                    cancelButtonText: "Annuler",
                    reverseButtons: true
                }).then((result) => {
                    if (result.value) {
                        e.currentTarget.submit();
                    }
                });
            }
        });
    </script>--}}
@endsection

resources/views/admins/slides/index.blade.php
@extends('admins.layouts.app')

@section('title')
    Slides
@endsection

@section('style')
{{--    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.css"/>--}}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css"/>
@endsection

{{--@section('script')
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#sortable").sortable();
            $("#sortable").disableSelection();
        });
    </script>
@endsection--}}

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item title-blue"><h2><b>{{__('Liste des slides')}}</b></h2></li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="search">
                            <div class="card-header">
                                <i class="fa fa-align-justify"></i>
                                Slides
                                <a class="pull-right btn btn-primary" href="{{ route('admin.slides.create') }}"><i
                                        class="fa fa-plus fa-lg"></i> <b>{{__('Add')}}</b></a>
                            </div>

                            <div class="card-body table-responsive">
                                <table id="table" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>@lang('Image')</th>
                                        <th>@lang('Title 1')</th>
                                        <th>@lang('Title 2')</th>
                                        <th>@lang('Button label')</th>
                                        <th>@lang('Button link')</th>
                                        <th>@lang('Button color')</th>
                                        <th>@lang('Actions')</th>
                                    </tr>
                                    </thead>
                                    <tbody id="table_contents">
                                    @foreach($slides as $slide)
                                        <tr class="row1" data-id="{{ $slide->id }}">
                                            <td>
                                                <img src="{{ $slide->image_url }}" alt=""
                                                     style="width: 100px; height: 50px;"/>
                                            </td>
                                            <td>{{ $slide->title1 }}</td>
                                            <td>{{ $slide->title2 }}</td>
                                            <td>{{ $slide->button_label }}</td>
                                            <td>{{ $slide->button_link }}</td>
                                            <td>
                                                {{ data_get(\App\Models\Button::COLORS, $slide->button_color) }}
                                            </td>
                                            <td>
                                                <div>
                                                    {!! Form::open(['route' => ['admin.slides.destroy', $slide->id], 'method' => 'delete']) !!}
                                                    <div class='btn-group'>
                                                        <a title="Voir" href="{{ route('admin.slides.show', $slide->id) }}" class='btn btn-ghost-success'>
                                                            <i class="fa fa-eye"></i>
                                                        </a>
                                                        <a title="Edit" href="{{ route('admin.slides.edit', $slide->id) }}" class='btn btn-ghost-info'>
                                                            <i class="fa fa-edit"></i>
                                                        </a>
                                                        {!! Form::button('<i class="fa fa-trash"></i>', [
                                                            'type' => 'submit',
                                                            'title' => 'Supprimer',
                                                            'class' => 'btn btn-ghost-danger',
                                                            'id' => 'delete_btn',
                                                            //'onclick' => "return confirm('Are you sure?')"
                                                        ]) !!}
                                                    </div>
                                                    {!! Form::close() !!}
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <tr>
                                    </tr>

                                </table>
                                <div class="pull-right mr-3">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

    <!-- jQuery UI -->
    <script type="text/javascript" src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Datatables Js-->
    <script type="text/javascript" src="//cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>

    <script>
        $('#table').DataTable({
            "language" : {
                "url" : "{{ asset('lang/' . config('app.locale') . '.json') }}"
            }
        });
    </script>

    <script type="text/javascript">
        $(function () {
            $("#table").DataTable();

            $("#table_contents").sortable({
                items: "tr",
                cursor: 'move',
                opacity: 0.6,
                update: function () {
                    sendOrderToServer();
                }
            });

            function sendOrderToServer() {

                var positions = [];
                $('tr.row1').each(function (index, element) {
                    positions.push({
                        id: $(this).attr('data-id'),
                        position: index + 1
                    });
                });

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "{{ url('admin/slide/position/update') }}",
                    data: {
                        positions: positions,
                        _token: '{{csrf_token()}}'
                    },
                });
            }
        });
    </script>

    <script type='text/javascript'>
        $(document).on("submit", "form", function (e) {
            e.preventDefault();
            Swal.fire({
                title: "{{__('Are you sure?') }}",
                html: "{{__('You won\'t be able to revert this!') }}",
                width: 400,
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#cbc7c1',
                confirmButtonText: "{{ __('Yes') }}",
                cancelButtonText: "{{ __('Cancel') }}",
                reverseButtons: true
            }).then((result) => {
                if (result.value) {
                    e.currentTarget.submit();
                }
            });
        });
    </script>
@endsection

resources/views/admins/slides/show.blade.php
@extends('admins.layouts.app')

@section('title')
    Detail Slide
@endsection

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.slides.index') }}">Slide</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('admin.slides.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('admins.slides.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/admins/slides/show_fields.blade.php
<!-- Image Field -->
<div class="form-group">
   {{-- {!! Form::label('image', 'Image:') !!}
    <p>{{ $slide->image }}</p>--}}
    <a data-toggle="dropdown" href="#">
        <img class="img-fluid width: 100%" src="{{ $slide->image_url }}" alt="" width="570"
             height="300" style="margin-bottom: 20px"/>
    </a>
</div>

<!-- Title1 Field -->
<div class="form-group">
    {!! Form::label('title1', 'Title1:') !!}
    <p>{{ $slide->title1 }}</p>
</div>

<!-- Title2 Field -->
<div class="form-group">
    {!! Form::label('title2', 'Title2:') !!}
    <p>{{ $slide->title2 }}</p>
</div>

<!-- Button Label Field -->
<div class="form-group">
    {!! Form::label('button_label', 'Button Label:') !!}
    <p>{{ $slide->button_label }}</p>
</div>

<!-- Button Link Field -->
<div class="form-group">
    {!! Form::label('button_link', 'Button Link:') !!}
    <p>{{ $slide->button_link }}</p>
</div>

<!-- Image Position Field -->
<div class="form-group">
    {!! Form::label('button_color', 'Button Color:') !!}
    <p>{{ $slide->button_color }}</p>
</div>

<!-- Image Position Field -->
<div class="form-group">
    {!! Form::label('image_position', 'Image Position:') !!}
    <p>{{ $slide->image_position }}</p>
</div>

resources/views/admins/slides/table.blade.php
@section('css')
    @include('admins.layouts.datatables_css')
@endsection

<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>

@section('scripts')
    @include('admins.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection