routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//home page routes
Route::get('/', 'HomePageController@index')->name('home.page');
Route::view('challenge/smart/unir', 'home_page/challenge_smart_unir')->name('challenge.smart.unir');
Route::view('programme/campagne', 'home_page/programme')->name('programme.campagne');
Route::view('croire/en/togo', 'home_page/croire')->name('croire');
Route::view('osons/davantage', 'home_page/osons_davantage')->name('osons');
Route::view('mot/president', 'home_page/mot_president')->name('mot.president');

Route::get('coming-soon/index', 'ComingSoonController@index')->name('coming_soon');

// Newsletter routes
Route::get('newsletter/store', 'Admin\NewsletterController@store')->name('store.newsletter');
Route::post('newsletter/store', 'Admin\NewsletterController@_store')->name('admin.store.newsletter');

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    Auth::routes();
    Route::get('/home', 'AdminHomeController@index')->name('home');
    Route::resource('buttons', 'ButtonController');

    Route::post('slide/position/update', 'SlideController@update_slide_position');
    Route::resource('slides', 'SlideController');

    Route::resource('newsletters', 'NewsletterController');
    Route::resource('newsletterMessages', 'NewsletterMessageController');

    Route::resource('parameters', 'ParameterController');
});

app/Models/Button.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class Button
 * @package App\Models
 * @version January 15, 2020, 6:12 pm UTC
 *
 * @property string label
 * @property string link
 * @property boolean visibility
 */
class Button extends Model
{

    public $table = 'buttons';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    const COLORS = ['color_white' => 'Blanc', 'color3' => 'Jaune', 'color4' => 'Bleu', 'color6' => 'Noir'];

    public $fillable = [
        'label',
        'color',
        'link',
        'visibility'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'label' => 'string',
        'link' => 'string',
        'visibility' => 'boolean'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'label' => ['required'],
        'link' => ['required', 'url'],
        'visibility' => 'required'
    ];

}

app/Http/Controllers/Admin/ButtonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\Admin\ButtonDataTable;
use App\Http\Requests\Admin\CreateButtonRequest;
use App\Http\Requests\Admin\UpdateButtonRequest;
use App\Models\Admin;
use App\Models\Button;
use App\Repositories\Admin\ButtonRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ButtonController extends AppBaseController
{
    /** @var  ButtonRepository */
    private $buttonRepository;

    public function __construct(ButtonRepository $buttonRepo)
    {
        $this->middleware('auth:' . Admin::GUARD);
        $this->buttonRepository = $buttonRepo;
    }

    /**
     * Display a listing of the Button.
     *
     * @param ButtonDataTable $buttonDataTable
     * @return Response
     */
    public function index(ButtonDataTable $buttonDataTable)
    {
        return $buttonDataTable->render('admins.buttons.index');
    }

    /**
     * Show the form for creating a new Button.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admins.buttons.create');
    }

    /**
     * Store a newly created Button in storage.
     *
     * @param CreateButtonRequest $request
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function store(CreateButtonRequest $request)
    {
        $input = $request->all();
        if($input['visibility']){
            $this->change_visible_btn();
        }
        if (!$input['color']){
           $input['color'] = 'color_white';
        }
        $button = $this->buttonRepository->create($input);

        Flash::success(__('Button saved successfully.'));

        return redirect(route('admin.buttons.index'));
    }

    /**
     * Display the specified Button.
     *
     * @param  int $id
     *
     * @return \Illuminate\View\View|\Illuminate\Routing\Redirector
     */
    public function show($id)
    {
        $button = $this->buttonRepository->find($id);

        if (empty($button)) {
            Flash::error(__('Button not found'));
            return redirect(route('admin.buttons.index'));
        }

        return view('admins.buttons.show')->with('button', $button);
    }

    /**
     * Show the form for editing the specified Button.
     *
     * @param  int $id
     *
     * @return\Illuminate\View\View|\Illuminate\Routing\Redirector
     */
    public function edit($id)
    {
        $button = $this->buttonRepository->find($id);

        if (empty($button)) {
            Flash::error(__('Button not found'));
            return redirect(route('admin.buttons.index'));
        }

        return view('admins.buttons.edit')->with('button', $button);
    }

    /**
     * Update the specified Button in storage.
     *
     * @param  int              $id
     * @param UpdateButtonRequest $request
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function update($id, UpdateButtonRequest $request)
    {
        $button = $this->buttonRepository->find($id);

        if (empty($button)) {
            Flash::error(__('Button not found'));
            return redirect(route('admin.buttons.index'));
        }
        if($request->all()['visibility']){
            $this->change_visible_btn();
        }
        $button = $this->buttonRepository->update($request->all(), $id);

        Flash::success(__('Button updated successfully.'));

        return redirect(route('admin.buttons.index'));
    }

    /**
     * Remove the specified Button from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $button = $this->buttonRepository->find($id);

        if (empty($button)) {
            Flash::error(__('Button not found'));
            return redirect(route('admin.buttons.index'));
        }

        $this->buttonRepository->delete($id);

        Flash::success(__('Button deleted successfully.'));

        return redirect(route('admin.buttons.index'));
    }

    public function change_visible_btn()
    {
        $visible_btn = Button::where('visibility', 1)->first();
        if ($visible_btn){
            $visible_btn->visibility = false;
            $visible_btn->save();
        }
    }
}

resources/views/admins/buttons/create.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Create Button')}}
@endsection

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('admin.buttons.index') !!}">{{__('Buttons')}}</a>
      </li>
      <li class="breadcrumb-item active">{{__('Create')}}</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>{{__('Create Button')}}</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'admin.buttons.store']) !!}

                                   @include('admins.buttons.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/admins/buttons/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.buttons.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    {{--<a href="{{ route('admin.buttons.show', $id) }}" class='btn btn-ghost-success' title="{{__('Show')}}">
       <i class="fa fa-eye"></i>
    </a>--}}
    <a href="{{ route('admin.buttons.edit', $id) }}" class='btn btn-ghost-info' title="{{__('Edit')}}">
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'title' => __('Delete'),
    ]) !!}
</div>
{!! Form::close() !!}

<script type='text/javascript'>
    $(document).on("submit", "form", function (e) {
        e.preventDefault();
        Swal.fire({
            title: "{{__('Are you sure?') }}",
            html: "{{__('You won\'t be able to revert this!') }}",
            width: 400,
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#cbc7c1',
            confirmButtonText: "{{ __('Yes') }}",
            cancelButtonText: "{{ __('Cancel') }}",
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                e.currentTarget.submit();
            }
        });
    });
</script>

resources/views/admins/buttons/edit.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Edit Button')}}
@endsection

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('admin.buttons.index') !!}">{{__('Buttons')}}</a>
          </li>
          <li class="breadcrumb-item active">{{__('Edit')}}</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>{{__('Edit Button')}}</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($button, ['route' => ['admin.buttons.update', $button->id], 'method' => 'patch']) !!}

                              @include('admins.buttons.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/admins/buttons/fields.blade.php
<!-- Label Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('label', __('Label:')) !!}</b>
    {!! Form::text('label', null, ['class' => 'form-control']) !!}
</div>

<!-- Link Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('link', __('Link:')) !!}</b>
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

<!-- -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('color', __('Color:')) !!}</b>
    {!! Form::select('color', \App\Models\Button::COLORS,
        null, ['placeholder' => __('Select the color'),'class' => 'form-control'])
    !!}
</div>

<!-- Visibility Field -->
<div class="form-group col-sm-6">
    <b>{!! Form::label('visibility', __('Visibility:')) !!}</b>
    <label class="checkbox-inline">
        {!! Form::hidden('visibility', 0) !!}
        {!! Form::checkbox('visibility', '1', null) !!}
    </label>
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('Save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('admin.buttons.index') }}" class="btn btn-secondary">{{__('Cancel')}}</a>
</div>

@section('styles')
    <link rel="stylesheet" href="{{ asset('template/css/selectize.bootstrap3.min.css') }}"/>
@endsection

<!-- Allows to search an option in select field -->
@section('scripts')
<script src="{{ asset('template/js/selectize.min.js') }}"></script>
<script>
    $(document).ready(function () {
        $('select').selectize({
            sortField: 'text'
        });
    });
</script>
@endsection

resources/views/admins/buttons/index.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Buttons')}}
@endsection

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item title-blue"><h2><b>{{__('List of buttons')}}</b></h2></li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             {{__('Buttons')}}
                             <a class="pull-right btn btn-primary" href="{{ route('admin.buttons.create') }}"><i class="fa fa-plus fa-lg"></i> <b>{{__('Add')}}</b></a>
                         </div>
                         <div class="card-body">
                             @include('admins.buttons.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/admins/buttons/show.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Detail Button')}}
@endsection

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.buttons.index') }}">Button</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('admin.buttons.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('admins.buttons.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/admins/buttons/show_fields.blade.php
<!-- Label Field -->
<div class="form-group">
    {!! Form::label('label', 'Label:') !!}
    <p>{{ $button->label }}</p>
</div>

<!-- Link Field -->
<div class="form-group">
    {!! Form::label('link', 'Link:') !!}
    <p>{{ $button->link }}</p>
</div>

<!-- Visibility Field -->
<div class="form-group">
    {!! Form::label('visibility', 'Visibility:') !!}
    <p>{{ $button->visibility }}</p>
</div>

resources/views/admins/buttons/table.blade.php
@section('css')
    @include('admins.layouts.datatables_css')
@endsection

<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>

@section('scripts')
    @include('admins.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection