routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//home page routes
Route::get('/', 'HomePageController@index')->name('home.page');
Route::view('challenge/smart/unir', 'home_page/challenge_smart_unir')->name('challenge.smart.unir');
Route::view('programme/campagne', 'home_page/programme')->name('programme.campagne');
Route::view('croire/en/togo', 'home_page/croire')->name('croire');
Route::view('osons/davantage', 'home_page/osons_davantage')->name('osons');
Route::view('mot/president', 'home_page/mot_president')->name('mot.president');

Route::get('coming-soon/index', 'ComingSoonController@index')->name('coming_soon');

// Newsletter routes
Route::get('newsletter/store', 'Admin\NewsletterController@store')->name('store.newsletter');
Route::post('newsletter/store', 'Admin\NewsletterController@_store')->name('admin.store.newsletter');

Route::prefix('admin')->namespace('Admin')->name('admin.')->group(function () {
    Auth::routes();
    Route::get('/home', 'AdminHomeController@index')->name('home');
    Route::resource('buttons', 'ButtonController');

    Route::post('slide/position/update', 'SlideController@update_slide_position');
    Route::resource('slides', 'SlideController');

    Route::resource('newsletters', 'NewsletterController');
    Route::resource('newsletterMessages', 'NewsletterMessageController');

    Route::resource('parameters', 'ParameterController');
});

app/Models/Newsletter.php
<?php

namespace App\Models;

use Eloquent as Model;

/**
 * Class Newsletter
 * @package App\Models
 * @version January 18, 2020, 12:46 pm UTC
 *
 * @property string email
 */
class Newsletter extends Model
{

    public $table = 'newsletters';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';




    public $fillable = [
        'email'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'email' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'Email' => ['required', 'string', 'email', 'max:255'],
    ];

}

app/Http/Controllers/Admin/NewsletterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\Admin\NewsletterDataTable;
use App\Http\Requests\Admin\CreateNewsletterRequest;
use App\Http\Requests\Admin\UpdateNewsletterRequest;
use App\Models\Newsletter;
use App\Repositories\Admin\NewsletterRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use MercurySeries\Flashy\Flashy;
use Response;
use App\Models\Admin;

class NewsletterController extends AppBaseController
{
    /** @var  NewsletterRepository */
    private $newsletterRepository;

    public function __construct(NewsletterRepository $newsletterRepo)
    {
        $this->middleware('auth:' . Admin::GUARD)->except('store');
        $this->newsletterRepository = $newsletterRepo;
    }

    /**
     * Display a listing of the Newsletter.
     *
     * @param NewsletterDataTable $newsletterDataTable
     * @return Response
     */
    public function index(NewsletterDataTable $newsletterDataTable)
    {
        return $newsletterDataTable->render('admins.newsletters.index');
    }

    /**
     * Show the form for creating a new Newsletter.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admins.newsletters.create');
    }

    /**
     * Store a newly created Newsletter in storage.
     *
     * @param CreateNewsletterRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateNewsletterRequest $request)
    {
        if (! Newsletter::where('email', '=', $request['Email'])->first()){
            Newsletter::create(['email' => $request['Email']]);
            Flashy::info(__("Thanks for subscribe to our newsletter"));

            return $request['coming-soon'] ? redirect()->route('coming_soon') :
                redirect()->route('home.page');
        }
        Flashy::info(__("Sorry! You have already subscribed"));

        return $request['coming-soon'] ? redirect()->route('coming_soon') : redirect()->route('home.page');
    }

    public function _store(Request $request)
    {
        $this->validate($request, [
            'email' => ['required', 'string', 'email', 'unique:newsletters', 'max:255'],
        ]);
        Newsletter::create(['email' => $request['email']]);
        Flash::success(__("Thanks for subscribe to our newsletter"));

        return redirect()->route('admin.newsletters.index');
    }

    /**
     * Display the specified Newsletter.
     *
     * @param  int $id
     *
     * @return \Illuminate\View\View|\Illuminate\Routing\Redirector
     */
    public function show($id)
    {
        $newsletter = $this->newsletterRepository->find($id);

        if (empty($newsletter)) {
            Flash::error('Newsletter not found');

            return redirect(route('admin.newsletters.index'));
        }

        return view('admins.newsletters.show')->with('newsletter', $newsletter);
    }

    /**
     * Show the form for editing the specified Newsletter.
     *
     * @param  int $id
     *
     * @return \Illuminate\View\View|\Illuminate\Routing\Redirector
     */
    public function edit($id)
    {
        $newsletter = $this->newsletterRepository->find($id);

        if (empty($newsletter)) {
            Flash::error('Newsletter not found');

            return redirect(route('admin.newsletters.index'));
        }

        return view('admins.newsletters.edit')->with('newsletter', $newsletter);
    }

    /**
     * Update the specified Newsletter in storage.
     *
     * @param  int              $id
     * @param UpdateNewsletterRequest $request
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function update($id, UpdateNewsletterRequest $request)
    {
        $newsletter = $this->newsletterRepository->find($id);

        if (empty($newsletter)) {
            Flash::error('Newsletter not found');

            return redirect(route('admin.newsletters.index'));
        }

        $newsletter = $this->newsletterRepository->update($request->all(), $id);

        Flash::success('Newsletter updated successfully.');

        return redirect(route('admin.newsletters.index'));
    }

    /**
     * Remove the specified Newsletter from storage.
     *
     * @param  int $id
     *
     * @return \Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        $newsletter = $this->newsletterRepository->find($id);

        if (empty($newsletter)) {
            Flash::error('Newsletter not found');

            return redirect(route('admin.newsletters.index'));
        }

        $this->newsletterRepository->delete($id);

        Flash::success('Newsletter deleted successfully.');

        return redirect(route('admin.newsletters.index'));
    }
}

resources/views/admins/newsletters/create.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Create')}} newsletter
@endsection

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('admin.newsletters.index') !!}">Newsletter</a>
      </li>
      <li class="breadcrumb-item active">{{__('Create')}}</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>{{__('Add an email to Newsletter')}}</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'admin.store.newsletter']) !!}

                                   @include('admins.newsletters.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/admins/newsletters/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.newsletters.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    {{--<a href="{{ route('admin.newsletters.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>--}}
    <a href="{{ route('admin.newsletters.edit', $id) }}" class='btn btn-ghost-info' title="{{__('Edit')}}">
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'title' => __('Delete'),
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/admins/newsletters/edit.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Edit newsletter')}}
@endsection

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('admin.newsletters.index') !!}">Newsletter</a>
          </li>
          <li class="breadcrumb-item active">{{__('Edit')}}</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Editer l'email</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($newsletter, ['route' => ['admin.newsletters.update', $newsletter->id], 'method' => 'patch']) !!}

                              @include('admins.newsletters.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/admins/newsletters/fields.blade.php
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', __('Email address:')) !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit(__('Save'), ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('admin.newsletters.index') }}" class="btn btn-secondary">{{__('Cancel')}}</a>
</div>

resources/views/admins/newsletters/index.blade.php
@extends('admins.layouts.app')

@section('title')
    Newsletters
@endsection

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item title-blue"><h2><b>{{__('List of subscribed emails')}}</b></h2></li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Newsletters
                             <a class="pull-right btn btn-primary" href="{{ route('admin.newsletters.create') }}">
                                 <i class="fa fa-plus fa-lg"></i> <b>{{__('Add')}}</b></a>
                         </div>
                         <div class="card-body">
                             @include('admins.newsletters.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/admins/newsletters/show.blade.php
@extends('admins.layouts.app')

@section('title')
    {{__('Detail')}} message
@endsection

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.newsletters.index') }}">Newsletter</a>
            </li>
            <li class="breadcrumb-item active">{{__('Detail')}}</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>{{__('Details')}}</strong>
                                  <a href="{{ route('admin.newsletters.index') }}" class="btn btn-light">{{__('Back')}}</a>
                             </div>
                             <div class="card-body">
                                 @include('admins.newsletters.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/admins/newsletters/show_fields.blade.php
<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $newsletter->email }}</p>
</div>

resources/views/admins/newsletters/table.blade.php
@section('css')
    @include('admins.layouts.datatables_css')
@endsection

<div class="table-responsive">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>

@section('scripts')
    @include('admins.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection